name: Update README based on feeds

on:
  workflow_dispatch:
  schedule:
    # Once a day at 8 AM
    - cron: 0 8 * * *

jobs:
  update-books:
    runs-on: ubuntu-latest
    steps:
      - uses: JasonEtco/rss-to-readme@v2
        with:
          feed-url: https://brainfck.org/tags/book/feed.xml
          readme-section: books
          template: "* {{ dateFinished }} [{{ title }}]({{ link }}))"
          branch: main
  update-blog-posts:
    runs-on: ubuntu-latest
    steps:
      - uses: JasonEtco/rss-to-readme@v2
        with:
          feed-url: https://blog.dornea.nu/feed.xml
          readme-section: blog
          branch: main
  update-tweets:
    runs-on: ubuntu-latest
    steps:
      - uses: JasonEtco/rss-to-readme@v2
        with:
          feed-url: "https://nitter.net/search/rss?f=tweets&q=victordorneanu"
          readme-section: twitter
          branch: main
